[package]
authors = ["Kenan Sulayman <kenan@sly.mn>"]
name = "eye_of_providence"
version = "0.1.0"

[dependencies]
afterparty = "0.2.0"
env_logger = "0.4.2"
hyper = "0.9.10"
json = "0.10.2"
log = "0.3.7"
regex = "0.2.1"
rouille = "2.1.0"
scoped_threadpool = "0.1.7"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
telegram-bot = "0.5.0"
url = "1.2.4"
urlshortener = "0.6.2"

[profile]

[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.release]
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "abort"
rpath = false
